# Generated by Django 4.2.1 on 2023-06-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contact_products_delete_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
