# Generated by Django 4.1.5 on 2023-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contact_products'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='categories',
    #         name='id',
    #     ),
    #     migrations.AddField(
    #         model_name='categories',
    #         name='cat_id',
    #         field=models.IntegerField(default=10, primary_key=True, serialize=False, unique=True),
    #     ),
    # ]
