# Generated by Django 4.1.5 on 2023-06-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_categories_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='cat_id',
        ),
    ]
