# Generated by Django 4.1.5 on 2023-06-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_categories_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
