# Generated by Django 4.1.5 on 2023-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_user_info_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=1),
        ),
    ]
