# Generated by Django 4.1.5 on 2023-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_img',
            field=models.ImageField(null=True, upload_to='cart_product'),
        ),
    ]
