# Generated by Django 4.2.1 on 2023-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_cart_cart_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
