# Generated by Django 4.1.5 on 2023-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
