# Generated by Django 4.1.5 on 2023-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_order_details_is_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='shipping',
            field=models.TextField(default='No special shipping'),
        ),
    ]
