# Generated by Django 4.2.1 on 2023-06-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_order_details_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='is_buy',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='total',
        ),
    ]
