# Generated by Django 4.1.5 on 2023-06-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_order_delete_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
